---
- name: Ensure the user is set
  fail: msg="Please set the 'vim_user' variable"
  when: vim_user is not defined

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600  # 1 hour

- name: Install vim
  apt:
    pkg:
      - vim
    state: present
