---
- name: Ensure the user is set
  fail: msg="Please set the 'vim_user' variable"
  when: vim_user is not defined

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600  # 1 hour

- name: Install vim
  apt:
    pkg:
      - vim
    state: present

- name: Write the vimrc
  copy:
    src: files/vimrc
    dest: /{{ vim_user }}/.vimrc
    backup: true
    owner: '{{ vim_user }}'
    group: '{{ vim_user }}'
    mode: 0644

- name: Make the autoload directory
  file:
    path: /{{ vim_user }}/.vim/autoload
    state: directory
    owner: '{{ vim_user }}'
    group: '{{ vim_user }}'
    mode: 0644

- name: Write plug.vim
  copy:
    src: files/vim/autoload/plug.vim
    dest: /{{ vim_user }}/.vim/autoload/plug.vim
    backup: true
    owner: '{{ vim_user }}'
    group: '{{ vim_user }}'
    mode: 0644

- name: Install vim plugins
  shell: 'vim -E -s -c "source /{{ vim_user }}/.vimrc" +PlugInstall +qall -V'  # noqa command-instead-of-shell no-changed-when
  changed_when: false  # This is necessary to make molecule happy - should figure out a way to only run when necessary
