---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Output of hello world
    command: "cat /var/hello_world"
    register: hello_world
    changed_when: false

  - name: Ensure we get the right output
    assert:
      that: hello_world.stdout == "Hello ansible!"
