---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    expected_vim_version: "VIM - Vi IMproved 8.0"
    expectd_vimrc_permissions: "-rw-r--r-- 1 root root"

  tasks:
    - name: Check output of vim --version
      command: "vim --version"
      register: vim_version
      changed_when: false

    - name: The right vim version was installed
      assert:
        that: expected_vim_version in (vim_version.stdout_lines | first)
        fail_msg: 'Expected {{ vim_version.stdout_lines | first }} to contain {{ expected_vim_version }}'

    - name: Stat the vimrc
      command: "ls -la /root/.vimrc"
      register: vimrc
      changed_when: false

    - name: Ensure the .vimrc exists
      assert:
        that: expectd_vimrc_permissions in vimrc.stdout
        fail_msg: 'Expected {{ vimrc.stdout }} to contain {{ expectd_vimrc_permissions }}'
